site_name: Loop Docs
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- 'index.md'
- Setup:
    - 'Overview': 'setup/overview.md'
    - Requirements:
        - 'Insulin Pump': 'setup/requirements/pump.md'
        - 'CGM': 'setup/requirements/cgm.md'
        - 'RileyLink': 'setup/requirements/rileylink.md'
        - 'Computer': 'setup/requirements/computer.md'
        - 'iPhone': 'setup/requirements/iphone.md'
        - 'Apple Developer': 'setup/requirements/appledev.md'
    - 'Install Loop':
        - 'Building App': 'setup/build/installing.md'
        - 'Build Errors': 'setup/build/build_errors.md'
        - 'Code Customization': 'setup/build/code_customization.md'
    - 'Loop App setup':
        - 'Health App': 'setup/loop-settings/health_app.md'
        - 'Settings': 'setup/loop-settings/settings.md'
        - 'Services': 'setup/loop-settings/services.md'
        - 'RileyLink menu': 'setup/loop-settings/rileylink_menu.md'
        - 'Pump settings': 'setup/loop-settings/pump.md'
    - 'Update':
        - 'Updating': 'setup/update/updating.md'
        - 'New Version Info': 'setup/update/new-version.md'
- Operation:
    - 'App Screens': 'operation/overview.md'
    - 'How To Loop':
        - 'Open Loop': 'operation/loop/open-loop.md'
        - 'Closed Loop': 'operation/loop/close-loop.md'
    - Features:
        - 'Apple Watch': 'operation/features/watch.md'
        - 'Bolus': 'operation/features/bolus.md'
        - 'Carb Entries': 'operation/features/carbs.md'
        - 'Health App': 'operation/features/healthapp.md'
        - 'iPhone widget': 'operation/features/widget.md'
        - 'Loop Notifications': 'operation/features/notifications.md'
        - 'Workout Targets': 'operation/features/workout.md'
    - Algorithm:
        - 'Overview': 'operation/algorithm/overview.md'
        - 'Bolus Recommendations': 'operation/algorithm/bolus.md'
        - 'Glucose Prediction': 'operation/algorithm/prediction.md'
        - 'Temp Basal Adjustments': 'operation/algorithm/temp_basal.md'
- Troubleshooting:
    - 'Overview': 'troubleshooting/overview.md'
    - 'Grey Loop': 'troubleshooting/green-loop.md'
    - 'Yellow/Red Loop': 'troubleshooting/yellow-red-loop.md'
    - 'NS display': 'troubleshooting/mlab_cleanup.md'
    - 'Priming and Sites': 'troubleshooting/priming.md'
    - 'RileyLink': 'troubleshooting/rileylink.md'
    - 'Time Changes': 'troubleshooting/time-change.md'
- Nightscout:
    - 'Overview': 'nightscout/overview.md'
    - 'Setup New Site': 'nightscout/new_user.md'
    - 'Update Site': 'nightscout/update_user.md'
    - 'Azure to Heroku': 'nightscout/azure_migration.md'
    - 'Loop Pill': 'nightscout/loop_pill.md'
    - 'IFTTT': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
    - 'Reports': 'nightscout/reports.md'
